const pt = {
  back: "Voltar ao dashboard",
  share: "Compartilhar",
  exportPdf: "Exportar PDF",
  branchLabel: "branch",
  filesLabel: "arquivos",
  langLabel: "linguagem principal",
  reportTitle: "Relatório de Análise",
  scoreLabel: "Pontuação geral",
  summaryLabel: "Resumo",
  strengthsTitle: "Pontos fortes",
  issuesTitle: "Problemas críticos",
  dimensionsTitle: "Análise por dimensão",
  recommendationsTitle: "Recomendações",
  tabs: {
    overview: "Visão geral",
    clean: "Código Limpo",
    patterns: "Padrões de Design",
    system: "Design de Sistema",
    practices: "Boas práticas",
    next: "Próximos passos",
  },
  overview: {
    dimScores: "Pontuação por dimensão",
    nextH: "Top 3 coisas para corrigir esta semana",
  },
  dimension: {
    positives: "O que está funcionando",
    improvements: "O que melhorar",
    evidence: "Evidências do seu código",
    openFile: "Abrir arquivo",
  },
  nextSteps: {
    blurb: "Ordenado por impacto/hora. Resolver o primeiro desbloqueia os próximos dois.",
    priority: "Prioridade",
    effort: "Esforço",
    impact: "Impacto",
  },
}

const en = {
  back: "Back to dashboard",
  share: "Share",
  exportPdf: "Export PDF",
  branchLabel: "branch",
  filesLabel: "files",
  langLabel: "primary language",
  reportTitle: "Analysis Report",
  scoreLabel: "Overall score",
  summaryLabel: "Summary",
  strengthsTitle: "Top strengths",
  issuesTitle: "Critical issues",
  dimensionsTitle: "Dimension analysis",
  recommendationsTitle: "Recommendations",
  tabs: {
    overview: "Overview",
    clean: "Clean Code",
    patterns: "Design Patterns",
    system: "System Design",
    practices: "Best practices",
    next: "Next steps",
  },
  overview: {
    dimScores: "Dimension breakdown",
    nextH: "Top 3 things to fix this week",
  },
  dimension: {
    positives: "What's working",
    improvements: "Where to push",
    evidence: "Evidence from your code",
    openFile: "Open file",
  },
  nextSteps: {
    blurb: "Ranked by impact-per-hour. Shipping the first one unlocks the next two.",
    priority: "Priority",
    effort: "Effort",
    impact: "Impact",
  },
}

export const reportCopy = { pt, en }
